### ISSUE TITLE
A URL for AMP Contributor Summit

### ISSUE THREAD

**Issue by tobie** [ampproject/amp.dev#1320]
## Objective

Have a persistent URL for the contributor summit.

## Background

A number of articles have been written by the press linking to the Google events page which is now a 404.

There's no place on the Web to link to when wanting to reference the contributor summit as a concept.

There is no place for past or future attendees to get a feel of what the event is, watch videos, download slides of talks, etc.

## Tasks
- [ ] create a web page for the contributor summit (e.g. at /contributor-summit)
- [ ] add link to youtube channel
- [ ] add video of keynote talk
- [ ] add agenda with links to slides and video of talks
- [ ] add links to unconf topics and session notes

**Comment by sebastianbenz** [comment]
//cc @alankent @mrjoro we should keep this in mind for this years contributor summit

**Comment by amanintech** [comment]
This can be closed now
