### ISSUE TITLE
Search: UX improvements

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/amp.dev#2972]
- [x] Don't submit search on type
- [x] Show a search button
- [x] Link to docs and samples from auto suggestions https://github.com/ampproject/amp.dev/issues/2864
- [x] Keyboard navigation in Safari https://github.com/ampproject/amp.dev/issues/2834
- [x] Migration to amp-lightbox https://github.com/ampproject/amp.dev/issues/2833
- [x] Enter should close keyboard on mobile https://github.com/ampproject/amp.dev/issues/2831

**Comment by sebil** [comment]
@sebastianbenz, while trying to finish this task:
> **_Link to docs and samples from auto suggestions #2864_**

I realized that currently this is not possible with the native `amp-autocomplete` component, because any click inside the list item will only select it. I guess there is a `preventDefault()` on the whole item element.

To make this work, we could try to make a feature request to get custom links in the autocomplete template.

I've build it with an `amp-mustache` template with links inside, see code and screenshot below:

```html
<template type="amp-mustache">
  <div data-value="{{name}}">
    <span>{{name}}</span>
    <a href="{{url}}"> […] </a>
    <a href="{{exampleUrl}}"> […] </a>
    <a href="{{playgroundUrl}}"> […] </a>
  </div>
</template>
```

![search-autocomplete-icons](https://user-images.githubusercontent.com/22053023/65583714-05f10400-df80-11e9-934e-10ccaf15a836.jpg)

**Comment by sebil** [comment]
Addendum:

Even if we renounce this feature, unfortunately it's not even possible to link the autocomplete items only to the docs pages. I've tried to do this with `navigateTo()` on the `select` event, but this only works with hard-coded strings, not with dynamic urls.

Either way we should do a feature request for `amp-autocomplete` to directly link items to specific urls and not only filling the input.

WDYT?

**Comment by sebastianbenz** [comment]
ah - too bad! Let's keep it simple then and only trigger the search on select.
