### ISSUE TITLE
[Meta] Cleanup and rename repository branches

### ISSUE THREAD

**Issue by danielrozenberg** [ampproject/amp.dev#6764]
I spoke with @powerivq about the state of branches in this repo. There's some confusing things happening here due to how this repo changed over time until now:

* The `master` branch is the original main branch of this repository, but is no longer used. GitHub redirects it to `static-production-amp-dev` (its last changes are available under `legacy-master`)
* `future` was the branch used for the last major rewrite of the website, and was the main branch for a while. It's also currently unused, and out of sync with the actual main branch:
* `static-production-amp-dev` is the current main branch of the repository. Pushes to it are automatically deployed to Netlify
* Various other branches were used in the past and no longer (e.g.: `production-amp-dev`, `legacy-master`, `legacy-production`)

We intend to fix this by:
- [x] **Renaming** `static-production-amp-dev` to `main`, making `main` the name of the main branch now
- [x] **Archiving** all the older branch
- [x] **Update the deployment job** to automatically deploy pushes to `main` to a staging environment on Netlify, and to have a manual trigger to deploy to production
